spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
razorpay.key_id=rzp_test_SlZXocB5864LwZ
razorpay.key_secret=VBIo8ol32NemWHz86Y2dP2y6